### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by cyjake** [cyjake/leoric#1]
The SQLite support for Jorma takes a bit more work than I thought when I started the work. I've [blogged it](http://cyj.me/programming/2018/01/11/programming-jorma-ii/)(in Chinese) a bit. But after digging the source of node-sqlite3 and SQLite itself further, I find the journey a little frustrating.

Currently, node-sqlite3 hasn't got a way to return fields along side the query results (see mapbox/node-sqlite3#433). I've opened a PR mapbox/node-sqlite3#932 to fix this issue using `sqlite3_column_table_name`. 

But even if with this pr accepted, the obstruction persists. `sqlite3_column_table_name` returns the original table name instead of the aliased one in SQL. For example, the table name returned in `SELECT foo.id AS foo_id FROM bar AS foo` is `bar`. To be fair, this makes sense since it always return the original table name. But there's no way to get the aliased one. 

A proper fields should be in following structure:

```js
[ { name, orgName, table, orgTable },
  { ... } ]
```

And given the SQL mentioned above, the fields should be:

```js
[ { name: 'foo_id', orgName: 'id', table: 'foo', orgTable: 'articles' } ]
```

A feature request is [proposed in 2014](http://sqlite.1065341.n5.nabble.com/sqlite-column-table-name-and-table-alias-name-td78959.html) but in vain. Hence I start digging the source of SQLite myself. Given the fact that the develop team behind SQLite use their own SCM, ticket system. A PR is highly unlikely. 

Another obstacle of adding SQLite support is date functions. Haven't got time to look into that though. 

- [x] add `sqlite_column_table_alias_name()` to properly support `nestTables`
- [x] use `strftime()` to substitute date functions such as `YEAR()`

**Comment by dotnil** [comment]
The original patch: http://mailinglists.sqlite.org/cgi-bin/mailman/private/sqlite-users/2014-November/056388.html
The key function to patch: https://github.com/mackyle/sqlite/blob/9b0af5fee9d73a97932f47dc51e45798e1c9a7af/src/select.c#L1363

**Comment by dotnil** [comment]
I've decided to use the fork for now, since I've got little response from both mapbox/node-sqlite#932 and the sqlite-users mail group. The original patch is extracted to [dotnil/node-sqlite3](https://github.com/dotnil/node-sqlite3/blob/master/deps/sqlite3.patch). 

Good news is the `sqlite3_column_table_alias_name()` might be available in the next release of SQLite. Let's see.

**Comment by dotnil** [comment]
Regarding the date functions, SQLite doesn't provide functions such as `YEAR()`, `MONTH()`. A general purpose [`strftime()`](https://www.sqlite.org/lang_datefunc.html) is provided instead. I've no intention to shim these methods with `stftime()`.

**Comment by cyjake** [comment]
with v0.5.0, SQLite is now supported without hacking node-sqlite3. Because table alias is unavailable in the metadata of query results, the columns will be enumerated and aliased according when querying SQLite databases, such as `SELECT foo.id AS foo:id`.

But there still are issues to fix:

- [ ] type check on primary key
- [ ] migration of table structure that contains primary key
