### ISSUE TITLE
[bug] $and AND $or with one value should work

### ISSUE THREAD

**Issue by JimmyDaddy** [cyjake/leoric#181]
```js

Model.find({
  where: {
     type: { $and: [ 'GOOD' ] }
  }
});

```
this will throw  `Cannot read property 'type' of undefined` at `src/drivers/abstract/spellbook.js:184:20`

**Comment by cyjake** [comment]
What is the expected behavior? ignore the `$and` or `$or` operator?

**Comment by JimmyDaddy** [comment]
> What is the expected behavior? ignore the `$and` or `$or` operator?

I think so, or is there another proper way?

**Comment by cyjake** [comment]
or throw an error telling the user that the operator didn't receive enough arguments. 

personally I'd go with ignore.
