### ISSUE TITLE
set `TINYINT` and `UNSIGNED INT` not working

### ISSUE THREAD

**Issue by luckydrq** [cyjake/leoric#279]
I'm using [egg-orm](https://github.com/eggjs/egg-orm) when encounting this problem and i think it is related with leoric.

Example: 
```typescript
import { Application } from 'egg';

export default (app: Application) => {
  const { STRING, INTEGER, DATE } = app.model.DataTypes;

  return app.model.define('User', {
    name: STRING,
    tinyInt: INTEGER('tiny'),
    unsignedInt: INTEGER('').UNSIGNED,
    deletedAt: DATE,
  }, {
    tableName: 'users',
  });
}
```

Table in database:

![image](https://user-images.githubusercontent.com/1474688/154884820-dc5ad09d-f3d2-4c71-8dbb-a91983f32e44.png)

**Comment by cyjake** [comment]
try this:

```js
const { STRING, INTEGER, DATE, TINYINT } = app.model.DataTypes;

app.model.define('User', {
  name: STRING,
  tinyInt: TINYINT,
  unsignedInt: INTEGER.UNSIGNED,
  deletedAt: DATE,
}
```

**Comment by luckydrq** [comment]
> try this:
> 
> ```js
> const { STRING, INTEGER, DATE, TINYINT } = app.model.DataTypes;
> 
> app.model.define('User', {
>   name: STRING,
>   tinyInt: TINYINT,
>   unsignedInt: INTEGER.UNSIGNED,
>   deletedAt: DATE,
> }
> ```

It seems that `TINYINT` not included in [DataTypes](https://github.com/cyjake/leoric/blob/master/types/data_types.d.ts#L8-L23). I will look into that later.

**Comment by cyjake** [comment]
yikes! `TINYINT` indeed is not supported yet. I'll look into it. 

btw, if the intention is use `TINYINT(1)` to represent boolean in MySQL, you can use BOOLEAN directly.

**Comment by luckydrq** [comment]
> 

Got
