### ISSUE TITLE
still alive?

### ISSUE THREAD

**Issue by PhilWaldmann** [cyjake/leoric#3]
Hey @dotnil 

I'll like your query syntax. Reminds me of  one of my projects: https://github.com/PhilWaldmann/openrecord

What do you think about working together on one project?

Cheers,
Philipp

**Comment by dotnil** [comment]
@PhilWaldmann 2018 has been rough but yeah there still are plans on this library. Glad you like the query syntax! I'll look into openrecord, for it looks promising and just blows jorma for its broad DBMS support.
