### ISSUE TITLE
Does dialect support dialectModule like sequelize.js ?

### ISSUE THREAD

**Issue by Beace** [cyjake/leoric#308]
![image](https://user-images.githubusercontent.com/13284978/167089686-f7e44944-a8f7-46c4-bf18-41fe4635863c.png)

**Comment by cyjake** [comment]
yep, you can use options.client to specify the actual client to be used to access database, such as:

```js
const realm = new Realm({
  dialect: 'sqlite',
  client: '@journeyapps/sqlcipher',
})
```

**Comment by cyjake** [comment]
https://sequelize.org/api/v7/interfaces/config#dialectModule
It looks like there are two options related to custom dialect module, opts.dialectModule for the module itself, and opts.dialectModulePath for the path of the module. To mimic the latter behavior, opts.dialectModulePath is now supported.
@Beace

**Comment by Beace** [comment]
OK, I will have a try later.
