### ISSUE TITLE
exports 配置变更兼容性问题

### ISSUE THREAD

**Issue by elrrrrrrr** [cyjake/leoric#415]
https://github.com/eggjs/tegg/blob/master/plugin/orm/lib/LeoricRegister.ts#L5

修改 exports 配置后，原来直接 import setupHook 的方式会报错

是否考虑提供单独接口或重新修改配置 🙏🏻

**Comment by cyjake** [comment]
我先修改一下 dist-tag，退到上一个 stable

hookNames 可以从 index export 出来

**Comment by cyjake** [comment]
我试试给 tegg 提个 pr

**Comment by cyjake** [comment]
https://github.com/eggjs/tegg/pull/174 @elrrrrrrr
