### ISSUE TITLE
Can we support pool for sqlite?

### ISSUE THREAD

**Issue by jianfenkezhan** [cyjake/leoric#60]
我们可以支持连接池吗？在一些老的 win7 平台，当有大量数据写入时，同时查询会变的特别慢。当我使用 sequelize 时，没有问题。是否可以使用 [node-pool](https://github.com/coopernurse/node-pool)来优化这个问题[](url)

**Comment by cyjake** [comment]
没问题，之前的 sqlite driver 有些原始，我看看如何优化

**Comment by jianfenkezhan** [comment]
可以，大佬看看我能做点什么贡献，可以分配给我。

**Comment by cyjake** [comment]
好呀，可以先讲讲你们使用 leoric 的场景吗？每个应用场景都很重要

**Comment by jianfenkezhan** [comment]
我们用 electron 做了一个应用，拿sqlite做了本地数据库，为了应用体验良好，使得离线弱网等场景下也能使用。初始化的时候，我会先获取本地数据库的数据，尽快展示，然后去服务端增量拉去新鲜的数据并且会同时存储（这个时候可能会有很多数据需要做存储），同时刻，例如我选择了一个 tab，或者我需要全局搜索某些东西等等场景，都是去本地数据查询数据。这时候获取数据非常慢，不成功。过一段时间在查询，就OK。

**Comment by cyjake** [comment]
@jianfenkezhan 抱歉这么晚才实现，现在支持通过 `connectionLimit` 来配置连接池大小了

**Comment by jianfenkezhan** [comment]
@cyjake 我们都是同事啦，已经没在负责这个东西了😂，我可以告诉老东家的同事去优化了

**Comment by cyjake** [comment]
@jianfenkezhan 👏 欢迎加入！有问题/建议随时提 issue 哈
